apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: helm-chart-deployment
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/40339090/guestbook
      imageSelectionStrategy: SemVer

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/40339090/kargo-helm.git
      includePaths:
      - base/feature-flags.yaml
