apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "guestbook.selectorLabels" . | nindent 4 }}
